export const TaskActionTypes = {
  ADD_NEW_TASK: 'TASK/ADD_NEW_TASK',
  EDIT_TASK_TITLE: 'TASK/EDIT_TASK_TITLE',
  SWITCH_COMPLETE_STATUS: 'TASK/SWITCH_COMPLETE_STATUS',
  DELETE_TASK: 'TASK/DELETE_TASK',
  DELETE_COMPLETED_TASKS: 'TASK/DELETE_COMPLETED_TASKS',
  SET_FILTER: 'TASK/SET_FILTER',
} as const;

export const InputTextActionTypes = {
  CHANGE: 'INPUT_TEXT/CHANGE',
  CLEAR: 'INPUT_TEXT/CLEAR',
} as const;
